### ISSUE TITLE
Bot should perhaps have an exit command

### ISSUE THREAD

**Issue by HuntingPhoenix** [SkyJedi/SWEotE-Discord-Dice-Roller#17]
I'm not sure there's a way to stop the bot from Discord.  That might be a nice addtion for self-hosted bots.

**Comment by SkyJedi** [comment]
Probably not going to add, self hosted bot can just kill the process (close terminal window) and adding a command would allow the Shared bot to be killed on command

**Comment by HuntingPhoenix** [comment]
Perhaps permissions controlled?  I'd like to find a way to have the bot run in the background.  If not, that's not the end of the world (or I might try to implement myself).

**Comment by SkyJedi** [comment]
!logout works as of (https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller/commit/dd9caf894271ab49068705cb3ebb621d3631cf5e)

you need to have the admin config filled out to use
