### ISSUE TITLE
wrong dice order

### ISSUE THREAD

**Issue by gustavoberman** [SkyJedi/SWEotE-Discord-Dice-Roller#21]
Hi there!
Sorry to bother
Sometimes the dice order differs from roll input to output printed:
The dice order printed out in this case should be ygrrpbk, but it is ygbrrpk

![imagen](https://user-images.githubusercontent.com/10926437/39056604-92245bd2-448d-11e8-8444-e090fef81e1e.png)

Thanks!

**Comment by SkyJedi** [comment]
The order is set to be ygbrpb
