### ISSUE TITLE
Bot listens for prefix in entire message

### ISSUE THREAD

**Issue by AndroidSalmon** [SkyJedi/SWEotE-Discord-Dice-Roller#22]
The bot currently listens for a prefix in the entire message instead of checking whether the message begins with the prefix or not. This creates some undesired behaviour when speaking in channels where the bot doesn't have external emoji set up:
(prefixes set up as ! and $ as examples)
![bot behaviour](https://i.imgur.com/z0YURYx.png)

**Comment by SkyJedi** [comment]
This is on purpose.  If you don't what the bot to respond in the channel toggle it's "read messages" permission rather than it's "external emoji" permission
