### ISSUE TITLE
char remove leaves an empty object

### ISSUE THREAD

**Issue by TimoThePirate** [SkyJedi/SWEotE-Discord-Dice-Roller#29]
When using the !char remove command it left the character with no attributes and only a name. Any attempts to recreate or modify the blank character would fail.

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/FFGNDS-Discord-Dice-Roller/commit/87aa983021a48d59bb10c2f2dc80fd9dbdf0abe6
