### ISSUE TITLE
Bot drops off channel

### ISSUE THREAD

**Issue by sudro2** [SkyJedi/SWEotE-Discord-Dice-Roller#34]
Periodically, the dice bot will go into "Offline" status on the chat channel. There seems no way to prompt it to rejoin with "Online" status. After a few minutes, the bot spontaneously rejoins.

**Comment by SkyJedi** [comment]
alrighty, i redid a bunch of memory caching optimization buzzwords, and its using less ram and is stable.  hopefully that improves stability
