### ISSUE TITLE
Dice roll from square bracket

### ISSUE THREAD

**Issue by caetheophei** [SkyJedi/SWEotE-Discord-Dice-Roller#38]
Hi,

We didn't add any prefix but the bot rolls dices when we type a text with square brackets
<img width="296" alt="example" src="https://user-images.githubusercontent.com/127054634/222985121-c820f793-98f0-430c-9e2e-bdda379b50e5.PNG">

**Comment by SkyJedi** [comment]
Not rolls dice when you use [].  That's what it does

**Comment by caetheophei** [comment]
Just to understand. We put a text between [] and we get dices and dice results (in the example, 2 success, 3 threats and 1 darkpipe).
If that's not a dice roll, what is it? And furthermore how we can it?

**Comment by SkyJedi** [comment]
[] will trigger the bot.  [Rrggb] will roll 2 red, 2 green, and a blue.
The bot pulls dice identifiers out of the text within []. It doesn't care
whats in the [] it going to roll all the dice identifiers with the []
